version: '3.8'

services:
  postgres_test:
    image: postgres:13
    container_name: test-db
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: test-db
    ports:
      - "5433:5432"  
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data: